college_code_mapping = {
    "A": "Antoinette Westphal COMAD",
    "AS": "Arts and Sciences",
    "B": "Bennett S. LeBow Coll. of Bus.",
    "CV": "Center for Civic Engagement",
    "C": "Close Sch of Entrepreneurship",
    "CI": "Col of Computing & Informatics",
    "E": "College of Engineering",
    "PH": "Dornsife Sch of Public Health",
    "GC": "Goodwin Coll of Prof Studies",
    "X": "Miscellaneous",
    "NH": "Nursing & Health Professions",
    "PE": "Pennoni Honors College",
    "R": "Sch.of Biomed Engr,Sci & Hlth",
    "T": "School of Education",
    "L": "Thomas R. Kline School of Law",
}


subject_codes = {
    "ANIM": "Animation (ANIM)",
    "ARCH": "Architecture (ARCH)",
    "ARTH": "Art History (ARTH)",
    "AAML": "Arts Admin & Museum Leadership (AAML)",
    "AADM": "Arts Administration (AADM)",
    "DANC": "Dance (DANC)",
    "DSMR": "Design & Merchandising (DSMR)",
    "DSRE": "Design Research (DSRE)",
    "DIGM": "Digital Media (DIGM)",
    "EAM": "Entertainment & Arts Managemnt (EAM)",
    "FASH": "Fashion Design (FASH)",
    "FMTV": "Film & TV Production (FMTV)",
    "FMST": "Film Studies (FMST)",
    "GMAP": "Game Art and Production (GMAP)",
    "VSCM": "Graphic Design (VSCM)",
    "IDM": "Interactive Digital Media (IDM)",
    "INTR": "Interior Design (INTR)",
    "MUSL": "Museum Leadership (MUSL)",
    "MUSC": "Music (MUSC)",
    "MIP": "Music Industry Program (MIP)",
    "PRFA": "Performing Arts (PRFA)",
    "PHTO": "Photography (PHTO)",
    "PROD": "Product Design (PROD)",
    "RMER": "Retail & Merchandising (RMER)",
    "SCRP": "Screenwriting & Playwriting (SCRP)",
    "TVST": "TV Studies (TVST)",
    "TVMN": "Television Management (TVMN)",
    "THTR": "Theatre (THTR)",
    "URBS": "Urban Strategy (URBS)",
    "VRIM": "VR and Immersive Media Design (VRIM)",
    "VSST": "Visual Studies (VSST)",
    "WEST": "WEST Studies (WEST)",
    "AFAS": "Africana Studies (AFAS)",
    "ANTH": "Anthropology (ANTH)",
    "ARBC": "Arabic (ARBC)",
    "BIO": "Bioscience & Biotechnology (BIO)",
    "CHEC": "Chemical Engineering Chemistry (CHEC)",
    "CHEM": "Chemistry (CHEM)",
    "CHIN": "Chinese (CHIN)",
    "COM": "Communication (COM)",
    "CCM": "Communication, Culture & Media (CCM)",
    "CW": "Creative Writing (CW)",
    "CJS": "Criminology & Justice Studies (CJS)",
    "ENGL": "English (ENGL)",
    "ESL": "English as a Second Language (ESL)",
    "ENSS": "Environ Stu & Sustainability (ENSS)",
    "ENVS": "Environmental Science (ENVS)",
    "FREN": "French (FREN)",
    "GEO": "Geoscience (GEO)",
    "GER": "German (GER)",
    "GST": "Global Studies (GST)",
    "HBRW": "Hebrew (HBRW)",
    "HIST": "History (HIST)",
    "ITAL": "Italian (ITAL)",
    "JAPN": "Japanese (JAPN)",
    "JWST": "Jewish Studies (JWST)",
    "KOR": "Korean (KOR)",
    "LING": "Linguistics (LING)",
    "MATH": "Mathematics (MATH)",
    "MENA": "Mid East & N African Studies (MENA)",
    "PHIL": "Philosophy (PHIL)",
    "PHYS": "Physics (PHYS)",
    "PHEV": "Physics-Environmental Science (PHEV)",
    "PSCI": "Political Science (PSCI)",
    "PSY": "Psychology (PSY)",
    "PLCY": "Public Policy (PLCY)",
    "SCTS": "Science Technology and Society (SCTS)",
    "SOC": "Sociology (SOC)",
    "SPAN": "Spanish (SPAN)",
    "WGST": "Women's and Gender Studies (WGST)",
    "WRIT": "Writing (WRIT)",
    "ACCT": "Accounting (ACCT)",
    "BSAN": "Business Analytics (BSAN)",
    "STAT": "Business Statistics (STAT)",
    "ECON": "Economics (ECON)",
    "FIN": "Finance (FIN)",
    "BUSN": "General Business (BUSN)",
    "HRMT": "Human Resource Management (HRMT)",
    "INDS": "Interdisciplinary Business (INDS)",
    "INTB": "International Business (INTB)",
    "BLAW": "Legal Studies-Business (BLAW)",
    "MGMT": "Management (MGMT)",
    "MIS": "Management Information Systems (MIS)",
    "MKTG": "Marketing (MKTG)",
    "OPM": "Operations Management (OPM)",
    "OPR": "Operations Research (OPR)",
    "ORGB": "Organizational Behavior (ORGB)",
    "POM": "Production Operations Mgmt (POM)",
    "PROJ": "Project Management (PROJ)",
    "REMD": "Real Estate Mgmt & Development (REMD)",
    "SMT": "Sport Management (SMT)",
    "TAX": "Taxation (TAX)",
    "CIVC": "Civic Engagement (CIVC)",
    "ENTP": "Entrepreneurship & Innovation (ENTP)",
    "CS": "Computer Science (CS)",
    "CT": "Computing Technology (CT)",
    "CI": "Computing and Informatics (CI)",
    "DSCI": "Data Science (DSCI)",
    "INFO": "Information Science & Systems (INFO)",
    "SE": "Software Engineering (SE)",
    "AE": "Architectural Engineering (AE)",
    "CHE": "Chemical Engineering (CHE)",
    "CAE": "Civil & Arch Engineering (CAE)",
    "CIVE": "Civil Engineering (CIVE)",
    "CAEE": "Civil, Arch & Envt Engineering (CAEE)",
    "CMGT": "Construction Management (CMGT)",
    "ECEC": "ECE - Computers (ECEC)",
    "ECEP": "ECE- Power (ECEP)",
    "ECES": "ECE- Systems (ECES)",
    "ECE": "Electrical & Comp Engineering (ECE)",
    "EET": "Electrical Engineering (EET)",
    "EGMT": "Engineering Management (EGMT)",
    "ENGR": "Engineering, General (ENGR)",
    "ENVE": "Environmental Engineering (ENVE)",
    "INDE": "Industrial Engineering (INDE)",
    "MET": "Manufacturing Engineering Tech (MET)",
    "MATE": "Materials Engineering (MATE)",
    "MEM": "Mech Engineering & Mechanics (MEM)",
    "PENG": "Peace Engineering (PENG)",
    "REAL": "Real Estate (REAL)",
    "SYSE": "Systems Engineering (SYSE)",
    "BST": "Biostatistics (BST)",
    "CHP": "Community Health & Prevention (CHP)",
    "EOH": "Environ & Occupational Health (EOH)",
    "EPI": "Epidemiology (EPI)",
    "HMP": "Health Management and Policy (HMP)",
    "PBHL": "Public Health (PBHL)",
    "FYE": "First-Year Exploratory Studies (FYE)",
    "GSTD": "General Studies (GSTD)",
    "NPM": "Nonprofit Management (NPM)",
    "PRST": "Professional Studies (PRST)",
    "EXAM": "Common Exams (EXAM)",
    "GES": "Global Engagement Scholar Prog (GES)",
    "MLSC": "Military Science (MLSC)",
    "NSC": "Naval Science (NSC)",
    "ABRD": "Study Abroad (ABRD)",
    "NUPR": "Advanced Professional Nursing (NUPR)",
    "BACS": "Behavioral & Addictions Couns (BACS)",
    "CIH": "Complement & Integrative Hlth (CIH)",
    "CIT": "Complement. & Integrative Ther (CIT)",
    "CFTX": "Counseling & Family Therapy (CFTX)",
    "CFTP": "Couple & Family Therapy (CFTP)",
    "CATX": "Creative Arts Therapies (CATX)",
    "CTCN": "Creative Therapies & Counsel (CTCN)",
    "CULA": "Culinary Arts (CULA)",
    "DMBC": "Drexel Med Coding & Billing (DMBC)",
    "FDSC": "Food Science (FDSC)",
    "HSCI": "Health Sciences (HSCI)",
    "HSAD": "Health Services Administration (HSAD)",
    "HRM": "Hotel & Restaurant Management (HRM)",
    "IPS": "Inter Professional Studies (IPS)",
    "NUAN": "Nurse Anesthesia (NUAN)",
    "NURS": "Nursing (NURS)",
    "NHP": "Nursing and Health Professions (NHP)",
    "NFS": "Nutrition & Food Science (NFS)",
    "PTRS": "Physical Therapy Rehab Science (PTRS)",
    "PA": "Physician Assistant (PA)",
    "RSCH": "Research (RSCH)",
    "CSDN": "Custom-Designed Major (CSDN)",
    "HNRS": "Honors Program (HNRS)",
    "BMES": "Biomedical Engineering & Sci (BMES)",
    "ABA": "Applied Behavior Analysis (ABA)",
    "CRTV": "Creativity Studies (CRTV)",
    "ELL": "E-Learning Leadership (ELL)",
    "EDGI": "Ed:Global & International Ed (EDGI)",
    "EDU": "Education (EDU)",
    "EDCR": "Education Core (EDCR)",
    "EHRD": "Education Human Resource Devel (EHRD)",
    "EDLT": "Education LearningTechnologies (EDLT)",
    "EDUP": "Education Practitioner (EDUP)",
    "EDUT": "Education Thesis (EDUT)",
    "EDAM": "Educational Administration (EDAM)",
    "EDLS": "Educational Lifelong Literacy (EDLS)",
    "EDPO": "Educational Policy (EDPO)",
    "EDHE": "Higher Education (EDHE)",
    "ISTM": "Interdisciplinary STEM (ISTM)",
    "MTED": "Mathematics Education (MTED)",
    "ESTM": "STEM Teacher Education (ESTM)",
    "EDSP": "School Psychology (EDSP)",
    "EDEX": "Special Education (EDEX)",
    "SCL": "Sport Coaching Leadership (SCL)",
    "EDUC": "Teacher Education (EDUC)",
    "LAW": "Law (LAW)",
    "LSTU": "Legal Studies (LSTU)",
}

col_to_courses = {
    "A": [
        "ANIM",
        "ARCH",
        "ARTH",
        "AAML",
        "AADM",
        "DANC",
        "DSMR",
        "DSRE",
        "DIGM",
        "EAM",
        "FASH",
        "FMTV",
        "FMST",
        "GMAP",
        "VSCM",
        "IDM",
        "INTR",
        "MUSL",
        "MUSC",
        "MIP",
        "PRFA",
        "PHTO",
        "PROD",
        "RMER",
        "SCRP",
        "TVST",
        "TVMN",
        "THTR",
        "URBS",
        "VRIM",
        "VSST",
        "WEST",
    ],
    "AS": [
        "AFAS",
        "ANTH",
        "ARBC",
        "BIO",
        "CHEC",
        "CHEM",
        "CHIN",
        "COM",
        "CCM",
        "CW",
        "CJS",
        "ENGL",
        "ESL",
        "ENSS",
        "ENVS",
        "FREN",
        "GEO",
        "GER",
        "GST",
        "HIST",
        "HBRW",
        "ITAL",
        "JAPN",
        "JWST",
        "KOR",
        "LING",
        "MATH",
        "MENA",
        "PHIL",
        "PHYS",
        "PHEV",
        "PSCI",
        "PSY",
        "PLCY",
        "SCTS",
        "SOC",
        "SPAN",
        "UNIV",
        "WGST",
        "WRIT",
    ],
    "B": [
        "ACCT",
        "BSAN",
        "STAT",
        "ECON",
        "FIN",
        "BUSN",
        "HRMT",
        "INDS",
        "INTB",
        "BLAW",
        "MGMT",
        "MIS",
        "MKTG",
        "OPM",
        "OPR",
        "ORGB",
        "POM",
        "PROJ",
        "REMD",
        "SMT",
        "TAX",
        "UNIV",
    ],
    "CV": ["CIVC"],
    "C": ["ENTP"],
    "CI": ["CS", "CT", "CI", "DSCI", "INFO", "SE", "UNIV"],
    "E": [
        "AE",
        "CHE",
        "CAE",
        "CIVE",
        "CAEE",
        "CMGT",
        "ECEC",
        "ECEP",
        "ECES",
        "ECE",
        "EET",
        "EGMT",
        "ENGR",
        "ENVE",
        "INDE",
        "MET",
        "MATE",
        "MEM",
        "PENG",
        "REAL",
        "SYSE",
    ],
    "PH": ["BST", "CHP", "EOH", "EPI", "HMP", "PBHL"],
    "GC": ["FYE", "GSTD", "NPM", "PRST"],
    "X": ["EXAM", "GES", "MLSC", "NSC", "ABRD"],
    "NH": [
        "NUPR",
        "BACS",
        "CIH",
        "CIT",
        "CFTX",
        "CFTP",
        "CATX",
        "CTCN",
        "CULA",
        "DMBC",
        "FDSC",
        "HSCI",
        "HSAD",
        "HRM",
        "IPS",
        "NUAN",
        "NURS",
        "NHP",
        "NFS",
        "PTRS",
        "PA",
        "RSCH",
        "UNIV",
    ],
    "PE": ["CSDN", "HNRS"],
    "R": ["BMES"],
    "T": [
        "ABA",
        "CRTV",
        "ELL",
        "EDGI",
        "EDU",
        "EDCR",
        "EHRD",
        "EDLT",
        "EDUP",
        "EDUT",
        "EDAM",
        "EDLS",
        "EDPO",
        "EDHE",
        "ISTM",
        "MTED",
        "ESTM",
        "EDSP",
        "EDEX",
        "SCL",
        "EDUC",
    ],
    "L": ["LAW", "LSTU"],
}
courses_to_col = {
    "ANIM": "A",
    "ARCH": "A",
    "ARTH": "A",
    "AAML": "A",
    "AADM": "A",
    "DANC": "A",
    "DSMR": "A",
    "DSRE": "A",
    "DIGM": "A",
    "EAM": "A",
    "FASH": "A",
    "FMTV": "A",
    "FMST": "A",
    "GMAP": "A",
    "VSCM": "A",
    "IDM": "A",
    "INTR": "A",
    "MUSL": "A",
    "MUSC": "A",
    "MIP": "A",
    "PRFA": "A",
    "PHTO": "A",
    "PROD": "A",
    "RMER": "A",
    "SCRP": "A",
    "TVST": "A",
    "TVMN": "A",
    "THTR": "A",
    "URBS": "A",
    "VRIM": "A",
    "VSST": "A",
    "WEST": "A",
    "AFAS": "AS",
    "ANTH": "AS",
    "ARBC": "AS",
    "BIO": "AS",
    "CHEC": "AS",
    "CHEM": "AS",
    "CHIN": "AS",
    "COM": "AS",
    "CCM": "AS",
    "CW": "AS",
    "CJS": "AS",
    "ENGL": "AS",
    "ESL": "AS",
    "ENSS": "AS",
    "ENVS": "AS",
    "FREN": "AS",
    "GEO": "AS",
    "GER": "AS",
    "GST": "AS",
    "HIST": "AS",
    "HBRW": "AS",
    "ITAL": "AS",
    "JAPN": "AS",
    "JWST": "AS",
    "KOR": "AS",
    "LING": "AS",
    "MATH": "AS",
    "MENA": "AS",
    "PHIL": "AS",
    "PHYS": "AS",
    "PHEV": "AS",
    "PSCI": "AS",
    "PSY": "AS",
    "PLCY": "AS",
    "SCTS": "AS",
    "SOC": "AS",
    "SPAN": "AS",
    "UNIV": "NH",
    "WGST": "AS",
    "WRIT": "AS",
    "ACCT": "B",
    "BSAN": "B",
    "STAT": "B",
    "ECON": "B",
    "FIN": "B",
    "BUSN": "B",
    "HRMT": "B",
    "INDS": "B",
    "INTB": "B",
    "BLAW": "B",
    "MGMT": "B",
    "MIS": "B",
    "MKTG": "B",
    "OPM": "B",
    "OPR": "B",
    "ORGB": "B",
    "POM": "B",
    "PROJ": "B",
    "REMD": "B",
    "SMT": "B",
    "TAX": "B",
    "CIVC": "CV",
    "ENTP": "C",
    "CS": "CI",
    "CT": "CI",
    "CI": "CI",
    "DSCI": "CI",
    "INFO": "CI",
    "SE": "CI",
    "AE": "E",
    "CHE": "E",
    "CAE": "E",
    "CIVE": "E",
    "CAEE": "E",
    "CMGT": "E",
    "ECEC": "E",
    "ECEP": "E",
    "ECES": "E",
    "ECE": "E",
    "EET": "E",
    "EGMT": "E",
    "ENGR": "E",
    "ENVE": "E",
    "INDE": "E",
    "MET": "E",
    "MATE": "E",
    "MEM": "E",
    "PENG": "E",
    "REAL": "E",
    "SYSE": "E",
    "BST": "PH",
    "CHP": "PH",
    "EOH": "PH",
    "EPI": "PH",
    "HMP": "PH",
    "PBHL": "PH",
    "FYE": "GC",
    "GSTD": "GC",
    "NPM": "GC",
    "PRST": "GC",
    "EXAM": "X",
    "GES": "X",
    "MLSC": "X",
    "NSC": "X",
    "ABRD": "X",
    "NUPR": "NH",
    "BACS": "NH",
    "CIH": "NH",
    "CIT": "NH",
    "CFTX": "NH",
    "CFTP": "NH",
    "CATX": "NH",
    "CTCN": "NH",
    "CULA": "NH",
    "DMBC": "NH",
    "FDSC": "NH",
    "HSCI": "NH",
    "HSAD": "NH",
    "HRM": "NH",
    "IPS": "NH",
    "NUAN": "NH",
    "NURS": "NH",
    "NHP": "NH",
    "NFS": "NH",
    "PTRS": "NH",
    "PA": "NH",
    "RSCH": "NH",
    "CSDN": "PE",
    "HNRS": "PE",
    "BMES": "R",
    "ABA": "T",
    "CRTV": "T",
    "ELL": "T",
    "EDGI": "T",
    "EDU": "T",
    "EDCR": "T",
    "EHRD": "T",
    "EDLT": "T",
    "EDUP": "T",
    "EDUT": "T",
    "EDAM": "T",
    "EDLS": "T",
    "EDPO": "T",
    "EDHE": "T",
    "ISTM": "T",
    "MTED": "T",
    "ESTM": "T",
    "EDSP": "T",
    "EDEX": "T",
    "SCL": "T",
    "EDUC": "T",
    "LAW": "L",
    "LSTU": "L",
}
